export const indianGirlsNamesByLetter = {
  a: new Set([
    "aadhya",
    "ayesha",
    "aarti",
    "ashu",
    "aaparna",
    "ananya",
    "anika",
    "aradhya",
    "akshara",
    "amrita",
    "anjali",
    "ayesha",
    "aaliya",
    "abha",
    "alka",
    "alisha",
    "ananya",
    "anshi",
    "anjali",
    "aruna",
    "asha",
    "ayesha",
    "anvi",
    "avani",
    "anita",
    "aashika",
    "aditi",
    "aparna",
    "aradhna",
    "archana",
    "ananya",
    "amita",
    "anita",
    "angela",
    "anu",
    "akshita",
    "arunima",
    "alina",
    "aseem",
    "aruna",
    "avika",
    "arundhati",
    "alisha",
    "archita",
    "ayushi",
    "anshika",
    "akansha",
    "akriti",
    "ambika",
    "alina",
    "asita",
    "anjali",
  ]),
  b: new Set([
    "bhavna",
    "bhavika",
    "bhawana",
    "bina",
    "binita",
    "barkha",
    "bansari",
    "beena",
    "bipasha",
    "balika",
    "bindu",
    "bhargavi",
    "bhoomika",
    "bindhya",
    "bhuvana",
    "binita",
    "bina",
    "binal",
    "bhavini",
    "bani",
    "bhavana",
    "bala",
    "barkha",
    "bhagyashree",
    "bandana",
    "bina",
    "basanti",
    "binita",
    "bhavisha",
    "bhavini",
    "binisha",
    "bimbi",
    "bansari",
    "babita",
    "baani",
    "bhavana",
    "bipasha",
    "bhavana",
    "bipasha",
    "binu",
    "balarani",
    "bindhya",
    "bhavini",
    "bhakti",
    "banshika",
    "bipasha",
  ]),
  c: new Set([
    "chandana",
    "charulata",
    "chitra",
    "chanchal",
    "chandni",
    "chhavi",
    "chaya",
    "chaitali",
    "charulata",
    "chandini",
    "chetana",
    "charmi",
    "chaaya",
    "chandni",
    "chandrika",
    "chaitali",
    "chhavi",
    "cindiya",
    "chirayu",
    "chakshi",
    "chavi",
    "chandrika",
    "charmi",
    "chandita",
    "chirpita",
    "chandni",
    "charita",
    "chinu",
    "charvi",
    "chandrika",
    "chaitali",
    "charita",
    "chintu",
    "chavi",
    "chirayu",
    "cinti",
    "chirasi",
    "chandan",
    "charmila",
    "chira",
    "chirag",
    "charvita",
    "chanchal",
    "chandana",
    "chiraya",
    "chitrani",
    "charishma",
    "charvi",
    "carrie",
    "chandni",
    "chanda",
  ]),
  d: new Set([
    "divya",
    "disha",
    "dimple",
    "deepika",
    "diya",
    "disha",
    "dhanvi",
    "darshita",
    "disha",
    "dimple",
    "deepa",
    "darpana",
    "divyani",
    "diya",
    "darshini",
    "deepa",
    "devika",
    "dhanvi",
    "disha",
    "dhriti",
    "disha",
    "daxina",
    "deepali",
    "dharini",
    "dhanvika",
    "disha",
    "divyani",
    "deepa",
    "diya",
    "diyana",
    "devika",
    "disha",
    "divisha",
    "dheevi",
    "dheera",
    "deeksha",
    "diya",
    "darshini",
    "disha",
    "devashree",
    "dinesha",
    "dipsika",
    "divya",
    "disha",
  ]),
  g: new Set([
    "gayathri",
    "geeta",
    "ganga",
    "gargi",
    "gitanjali",
    "garima",
    "gunjan",
    "gini",
    "gita",
    "geeta",
    "gargi",
    "gita",
    "ganga",
    "grishma",
    "gitali",
    "geetika",
    "gunisha",
    "gargee",
    "gita",
    "guneeta",
    "gajala",
    "ganga",
    "gauri",
    "gargi",
    "guni",
    "grace",
    "giri",
    "gagan",
    "gayatri",
    "giti",
    "gajal",
    "gouri",
    "ganga",
    "gana",
    "garima",
    "gaurika",
    "giti",
    "gurneet",
    "gargi",
    "grishma",
    "gunika",
    "garvya",
    "geetika",
    "giri",
    "gayan",
    "gauravi",
    "gundi",
    "gini",
  ]),
  i: new Set([
    "indira",
    "ishita",
    "ishwari",
    "imran",
    "imarti",
    "indira",
    "isha",
    "indu",
    "indu",
    "indira",
    "indra",
    "isha",
    "idika",
    "ishita",
    "ishwari",
    "ipsha",
    "indrayani",
    "indee",
    "izara",
    "ikra",
    "ishita",
    "inaya",
    "indira",
    "indee",
    "isha",
    "imara",
    "iksha",
    "inaara",
    "imra",
    "ikra",
    "idika",
    "indira",
    "ishwari",
    "ishara",
    "inika",
    "india",
    "indira",
    "iksha",
    "ichha",
    "inika",
    "irisha",
    "ishita",
    "indira",
    "isha",
    "indira",
    "insha",
    "ishara",
    "ikra",
  ]),
  j: new Set([
    "jaya",
    "janani",
    "jahnavi",
    "jalpa",
    "jasmine",
    "jagruti",
    "juhi",
    "jaya",
    "juhi",
    "jaya",
    "jhanvi",
    "jalpa",
    "jaya",
    "jahnavi",
    "jalpa",
    "jyoti",
    "jaya",
    "jisha",
    "jamine",
    "joyti",
    "jiya",
    "jagruti",
    "jayanti",
    "jini",
    "juhi",
    "jovita",
    "janaki",
    "jinisha",
    "jalpa",
    "julia",
    "janvi",
    "jagruthi",
    "jameela",
    "jhanvi",
    "jinesh",
    "jahnavi",
    "jalini",
    "jyothi",
    "janani",
    "juhi",
    "jayati",
    "julia",
    "jinika",
    "jashika",
    "jyotika",
    "jovita",
    "junita",
  ]),
  k: new Set([
    "kajal",
    "kanika",
    "kavitha",
    "kavya",
    "komal",
    "kriti",
    "kiran",
    "kamini",
    "karishma",
    "khushboo",
    "kushala",
    "kanchan",
    "karishma",
    "kavitha",
    "kavya",
    "kirti",
    "kiran",
    "khushboo",
    "kanak",
    "kamna",
    "karuna",
    "kumud",
    "kiran",
    "kanika",
    "kanchan",
    "kashish",
    "kavita",
    "komal",
    "karan",
    "kaveri",
    "kavitha",
    "kiran",
    "kanak",
    "kanta",
    "kavya",
    "kamini",
    "kanika",
    "kaushiki",
    "kiran",
    "kanchan",
    "kavitha",
    "kavya",
    "kriti",
    "kavita",
    "kavina",
    "kamani",
    "kamini",
    "kashika",
    "karuna",
    "kanchana",
    "karishma",
    "khushbu",
    "kavya",
    "kamna",
    "kanaka",
  ]),
  l: new Set([
    "lavanya",
    "lakshmi",
    "lily",
    "leela",
    "laxmi",
    "lalita",
    "lamiya",
    "lasha",
    "laasya",
    "lavitha",
    "lovely",
    "leena",
    "lira",
    "laksha",
    "lalitha",
    "laxita",
    "linga",
    "lasya",
    "laxmi",
    "leela",
    "luvena",
    "livia",
    "lakshmi",
    "limra",
    "lina",
    "laxmi",
    "lavanya",
    "laksha",
    "lily",
    "lira",
    "lavina",
    "leela",
    "lisa",
    "linta",
    "lucky",
    "liya",
    "lilani",
    "lora",
    "lalitha",
    "laasya",
    "lima",
    "linga",
    "lovisha",
    "lavita",
    "lasa",
    "lira",
    "linga",
    "lina",
  ]),
  m: new Set([
    "manasi",
    "mansi",
    "manju",
    "madhavi",
    "madhuri",
    "meenal",
    "meera",
    "mitali",
    "manisha",
    "mahi",
    "madhu",
    "madhavi",
    "manisha",
    "mahi",
    "mandira",
    "manju",
    "meenal",
    "manasi",
    "madhavi",
    "mahi",
    "maisha",
    "madhuri",
    "manju",
    "meher",
    "madhavi",
    "manika",
    "madhuri",
    "manju",
    "meera",
    "meenal",
    "madhavi",
    "manali",
    "manjula",
    "maisha",
    "madhuri",
    "manasvi",
    "mahi",
    "manpreet",
    "manasi",
    "monika",
    "meera",
    "manisha",
    "maisha",
    "manasi",
    "mahi",
    "maisha",
    "madhavi",
  ]),
  n: new Set([
    "nidhi",
    "neha",
    "neelam",
    "nisha",
    "nimisha",
    "nupur",
    "naina",
    "nidhi",
    "navya",
    "nikita",
    "nehal",
    "naina",
    "neha",
    "nithya",
    "nashita",
    "nithisha",
    "nayana",
    "nisha",
    "naitra",
    "neha",
    "nupur",
    "nisha",
    "nehal",
    "nina",
    "nitya",
    "nishi",
    "neerja",
    "neelam",
    "nivedita",
    "nikita",
    "navika",
    "nayana",
    "neera",
    "neha",
    "nishtha",
    "nidi",
    "noor",
    "nisha",
    "nazia",
    "neena",
    "nashita",
    "nisha",
    "nishka",
    "nisha",
    "nashika",
    "neelima",
    "nirja",
    "neema",
    "nina",
  ]),
  o: new Set([
    "oindrila",
    "omika",
    "opasha",
    "orchid",
    "oyinda",
    "olivia",
    "omita",
    "ojaswi",
    "oza",
    "osheen",
    "omika",
    "oonika",
    "opsha",
    "ostana",
    "ornella",
    "otika",
    "oza",
    "omisha",
    "osha",
    "oindri",
    "osheen",
    "ousha",
    "orchida",
    "omisha",
    "ornela",
    "onika",
    "olivia",
    "oshini",
    "oora",
    "ostana",
    "opasha",
    "omra",
    "omika",
    "olva",
    "olvi",
    "orchid",
    "omika",
    "omisha",
    "olisha",
    "omita",
    "oshaa",
    "oja",
    "oshika",
    "obika",
    "omani",
  ]),
  p: new Set([
    "pallavi",
    "parul",
    "parvati",
    "pooja",
    "pragya",
    "pranjal",
    "priya",
    "pragya",
    "pavitra",
    "poornima",
    "poonam",
    "pranjali",
    "priti",
    "pranali",
    "pragati",
    "purnima",
  ]),
  q: new Set([
    "queen",
    "quira",
    "qiran",
    "quashi",
    "quarna",
    "qulfiya",
    "qisma",
    "qunita",
    "quamar",
    "qaseem",
    "qutbiya",
    "qubira",
    "qita",
    "qashifa",
    "qulfiya",
    "qisma",
    "qubira",
    "quriya",
    "qamar",
    "quayla",
    "quayara",
  ]),
  r: new Set([
    "rahi",
    "rajan",
    "radhika",
    "rani",
    "reva",
    "rekha",
    "richa",
    "ritu",
    "roopa",
    "rupali",
    "rupal",
    "riya",
    "ravi",
    "rupa",
    "ruchi",
    "ritu",
    "raisha",
    "ramya",
    "ragini",
    "reva",
    "rupal",
    "ruchika",
    "ritika",
    "richa",
    "rishika",
    "riya",
    "reema",
    "ruhi",
    "rupal",
    "rhea",
    "roshni",
    "rubina",
    "rubina",
    "roshni",
    "ragini",
    "riya",
    "reema",
    "ranita",
    "rupal",
    "ruchita",
    "ridhima",
    "rashi",
    "rahel",
    "riya",
    "roshini",
  ]),
  s: new Set([
    "sanya",
    "sarika",
    "shakshi",
    "shalini",
    "shanti",
    "shreya",
    "sia",
    "simran",
    "sneha",
    "sohini",
    "sonali",
    "sonakshi",
    "surbhi",
    "sushma",
    "swathi",
    "shubhi",
    "sara",
    "sindhu",
    "simi",
    "sindhuri",
    "shruti",
    "sonika",
    "suman",
    "shivani",
    "supriya",
    "seema",
    "surbhi",
    "suman",
    "sai",
    "sunita",
    "shreya",
    "shilpa",
    "sujata",
    "sangeeta",
    "shweta",
    "shaila",
    "smita",
    "shivangi",
    "shivani",
    "sheela",
    "shivani",
    "sapna",
    "shikha",
    "shweta",
    "seema",
    "simran",
    "sakshi",
    "sonali",
    "shubhi",
  ]),
  t: new Set([
    "tanya",
    "tanisha",
    "tara",
    "trisha",
    "tanuja",
    "tina",
    "tanu",
    "thara",
    "tulsi",
    "twinkle",
    "tashi",
    "tasmina",
    "trisha",
    "tapasi",
    "tritiya",
    "tarini",
    "tharini",
    "tulika",
    "tanya",
    "tithi",
    "tanu",
    "tapti",
    "tavisha",
    "tushita",
    "tejika",
    "tanuja",
    "tanika",
    "tasha",
    "tanshi",
    "tanvi",
    "tanu",
    "tara",
    "trisha",
    "trisha",
    "tanisha",
    "tanya",
    "tanuja",
    "tapti",
    "tasha",
    "tithira",
    "tapti",
    "tanu",
    "tanvi",
    "tulsi",
  ]),
  u: new Set([
    "urvi",
    "usha",
    "utkarsha",
    "urvashi",
    "umisha",
    "upasana",
    "utpal",
    "utsavi",
    "urshita",
    "urja",
    "ugra",
    "unisha",
    "umeesha",
    "upma",
    "utka",
    "udisha",
    "uchita",
    "upeksha",
    "utini",
    "ushika",
    "urvi",
    "usha",
    "utpreet",
    "urvi",
    "ushita",
    "upali",
    "umama",
    "urshika",
    "ushmita",
    "urvashi",
    "ubika",
    "usha",
    "urvitha",
    "uneeka",
    "uni",
    "uttara",
  ]),
  v: new Set([
    "vidya",
    "vibhuti",
    "vasundhara",
    "vandana",
    "vasudha",
    "vidushi",
    "vanshika",
    "vani",
    "vibha",
    "vaishnavi",
    "vishakha",
    "vibha",
    "vibha",
    "vidya",
    "varsha",
    "vaidehi",
    "vidushi",
    "vatsala",
    "vani",
    "vibhuti",
    "virti",
    "vani",
    "vrishti",
    "vanshika",
    "vasundhara",
    "vishal",
    "vibha",
    "vriti",
    "varsha",
    "vaidehi",
    "vasudha",
    "vasundhara",
    "vani",
    "vidushi",
    "vidya",
    "vrishika",
    "vani",
    "vanshika",
    "vasundhara",
  ]),
  w: new Set([
    "wafa",
    "waseem",
    "wasiqa",
    "wazifa",
    "waliya",
    "wajiha",
    "warisha",
    "wazira",
    "wajida",
    "wasima",
    "waliya",
    "wafa",
    "wasiqa",
    "wahida",
    "wazifa",
    "warishta",
    "waliya",
    "wajida",
    "wasiqa",
    "wafa",
    "wasima",
    "wazifa",
    "warisa",
    "wazira",
    "waliya",
    "wajiha",
  ]),
  x: new Set([
    "xara",
    "xena",
    "xiamara",
    "xandra",
    "xarifa",
    "xylia",
    "xenia",
    "xiya",
    "xia",
    "xara",
    "xandra",
    "xania",
    "xenobia",
    "xiya",
    "xita",
    "xara",
    "xylia",
    "xarina",
    "xandra",
    "xenia",
  ]),
  y: new Set([
    "yamini",
    "yami",
    "yashika",
    "yogita",
    "yukta",
    "yashika",
    "yogini",
    "yumna",
    "yasmin",
    "yusra",
    "yashvi",
    "yukta",
    "yogi",
    "yashvi",
    "yashita",
    "yogita",
    "yukti",
    "yumi",
    "yashvi",
    "yasmine",
    "yuktha",
    "yasmeen",
    "yogita",
    "yajna",
    "yajvi",
    "yashika",
    "yami",
    "yamika",
  ]),
  z: new Set([
    "zara",
    "zainab",
    "zahra",
    "zanisha",
    "zain",
    "zaiba",
    "zara",
    "zainab",
    "zoya",
    "zainisha",
    "zahira",
    "zarina",
    "zarina",
    "zoha",
    "zulekha",
    "zara",
    "zain",
    "zunaira",
    "zaid",
    "zoha",
    "zahira",
    "zaara",
    "zaheen",
  ]),
} as { [key: string]: Set<string> };

export const ABC: { id: number; value: string }[] = [
  { id: 0, value: "A" },
  { id: 1, value: "B" },
  { id: 2, value: "C" },
  { id: 3, value: "D" },
  { id: 4, value: "E" },
  { id: 5, value: "F" },
  { id: 6, value: "G" },
  { id: 7, value: "H" },
  { id: 8, value: "I" },
  { id: 9, value: "J" },
  { id: 10, value: "K" },
  { id: 11, value: "L" },
  { id: 12, value: "M" },
  { id: 13, value: "N" },
  { id: 14, value: "O" },
  { id: 15, value: "P" },
  { id: 16, value: "Q" },
  { id: 17, value: "R" },
  { id: 18, value: "S" },
  { id: 19, value: "T" },
  { id: 20, value: "U" },
  { id: 21, value: "V" },
  { id: 22, value: "W" },
  { id: 23, value: "X" },
  { id: 24, value: "Y" },
  { id: 25, value: "Z" },
];

export const EMOJIS: { id: number; value: string }[] = [
  { id: 0, value: "😊" },
  { id: 1, value: "😍" },
  { id: 2, value: "😎" },
  { id: 3, value: "🥺" },
  { id: 4, value: "😂" },
  { id: 5, value: "🤔" },
  { id: 6, value: "🙌" },
  { id: 7, value: "💥" },
  { id: 8, value: "🌟" },
  { id: 9, value: "🔥" },
  { id: 10, value: "🌈" },
  { id: 11, value: "🍕" },
  { id: 12, value: "🍎" },
  { id: 13, value: "🎉" },
  { id: 14, value: "⚽" },
  { id: 15, value: "🎶" },
  { id: 16, value: "🎨" },
  { id: 17, value: "🐶" },
  { id: 18, value: "🐱" },
  { id: 19, value: "🦄" },
  { id: 20, value: "🍩" },
  { id: 21, value: "🎁" },
  { id: 22, value: "🥳" },
  { id: 23, value: "🤗" },
  { id: 24, value: "💫" },
  { id: 25, value: "🌻" },
  { id: 26, value: "🌍" },
  { id: 27, value: "🌙" },
  { id: 28, value: "💖" },
  { id: 29, value: "🎃" },
  { id: 30, value: "🦋" },
  { id: 31, value: "🐝" },
  { id: 32, value: "🐦" },
  { id: 33, value: "🍇" },
  { id: 34, value: "🥑" },
  { id: 35, value: "🍔" },
  { id: 36, value: "🍓" },
  { id: 37, value: "🧩" },
  { id: 38, value: "🏀" },
  { id: 39, value: "🏖" },
  { id: 40, value: "🌵" },
  { id: 41, value: "🌊" },
  { id: 42, value: "🎮" },
  { id: 43, value: "🧸" },
  { id: 44, value: "🍿" },
  { id: 45, value: "🍿" },
  { id: 46, value: "🧑‍🎤" },
  { id: 47, value: "🎩" },
  { id: 48, value: "💌" },
  { id: 49, value: "👑" },
  { id: 50, value: "🧃" },
  { id: 51, value: "🥂" },
  { id: 52, value: "🍺" },
  { id: 53, value: "🌸" },
];

export const SHAPES: { id: number; value: string }[] = [
  { id: 0, value: "◯" },
  { id: 1, value: "◼" },
  { id: 2, value: "△" },
  { id: 3, value: "★" },
  { id: 4, value: "☆" },
  { id: 5, value: "□" },
  { id: 6, value: "◇" },
  { id: 7, value: "▭" },
  { id: 8, value: "▯" },
  { id: 9, value: "◯" },
  { id: 10, value: "▮" },
  { id: 11, value: "◠" },
  { id: 12, value: "⊙" },
  { id: 13, value: "⊛" },
  { id: 14, value: "⊜" },
  { id: 15, value: "⧫" },
  { id: 16, value: "⧴" },
  { id: 17, value: "➖" },
  { id: 18, value: "➗" },
  { id: 19, value: "⟁" },
  { id: 20, value: "▸" },
  { id: 21, value: "◁" },
  { id: 22, value: "⚪" },
  { id: 23, value: "⚫" },
  { id: 24, value: "✧" },
  { id: 25, value: "✩" },
  { id: 26, value: "⋆" },
  { id: 27, value: "⧫" },
  { id: 28, value: "▤" },
  { id: 29, value: "⟁" },
  { id: 30, value: "≡" },
  { id: 31, value: "⩰" },
  { id: 32, value: "⩷" },
  { id: 33, value: "◯" },
  { id: 34, value: "⨀" },
  { id: 35, value: "⊙" },
  { id: 36, value: "◯" },
  { id: 37, value: "◇" },
  { id: 38, value: "■" },
  { id: 39, value: "➰" },
];

export const appreciationLines: string[] = [
  "Amazing job! You're a memory master!",
  "You did it! What a memory genius!",
  "Incredible! You're unstoppable!",
  "Fantastic! Your memory is on fire!",
  "Unbelievable! You have the sharpest mind!",
  "Bravo! You crushed the game!",
  "Outstanding! Your memory is top-notch!",
  "Well done! You're a memory champion!",
  "Impressive! You've got memory skills like no other!",
  "Perfect! Your memory is flawless!",
  "Victory is yours! Great job!",
  "Superb! You're a memory legend!",
  "You’re on a roll! Keep up the great work!",
  "Unstoppable! You're a memory machine!",
  "Mind-blowing! You've mastered the game!",
  "You nailed it! Your memory is second to none!",
  "You're a genius! What a performance!",
  "You're crushing it! Memory expert in the making!",
  "Keep it up! Your memory is simply amazing!",
  "You're on fire! Another win in the books!",
  "Wow! Your memory is next-level!",
  "Incredible focus! You’re a memory master!",
  "Your brain is a powerhouse! Fantastic work!",
  "You’ve got the best memory in the game!",
  "You're unstoppable! Keep showing off those skills!",
  "Wow, just wow! You’ve got a memory like a steel trap!",
  "Impressive! You've got a memory that can’t be beat!",
  "Mind sharp as a tack! You've got this down!",
  "Sensational! You remember everything like a pro!",
  "Perfection! Your memory is the gold standard!",
  "You’re a memory expert! Keep it up!",
  "Simply brilliant! You made it look easy!",
  "What a win! Your memory skills are unparalleled!",
  "That was amazing! Your mind is a marvel!",
  "You're a memory magician! Tricks and all!",
  "Champion status achieved! Incredible memory!",
  "You're a memory wizard! Well played!",
  "Top-notch work! Your brain is amazing!",
  "Like a memory prodigy! Excellent job!",
  "Total victory! Your memory is unbeatable!",
  "You did it! Your memory is truly impressive!",
  "Absolutely fantastic! You're a memory mastermind!",
  "Awesome work! You’ve got a memory like no other!",
];

export const CardTypes: { id: number; val: string; type: string }[] = [
  { id: 0, val: "😁😉", type: "EMOJIS" },
  { id: 1, val: "ABC", type: "ABC" },
  { id: 2, val: "123", type: "NUM" },
  { id: 3, val: "◯◼△", type: "SHAPES" },
];
